services:
  - type: web
    name: telegram-rich-bike-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: CITY
        value: Ташкент
      - key: GROUP_CHAT_ID
        value: "-4851152519,-1004851152519"
